
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/wedding-template4/"
url: https:crux-wedding.github.io


# Build settings
markdown: kramdown

navbar-menu:
  - name: Our Story
    url: ourstory

  - name: Event Details
    url: event-detail

  - name: RSVP
    url: rsvp

cover:
  couple-name: "Joey + Christine"
  wedding-date: "10-05-2016"

content:
  - id: ourstory
    title: Our Story
    image: "content-image.jpg"
    description: Cras varius, nunc et maximus ullamcorper, tellus tellus posuere ipsum, ac tincidunt orci tortor id sapien. Vivamus ultrices purus id nisl volutpat, et placerat nisi ultricies. Integer at vehicula elit. Ut non velit non dui finibus finibus. Duis feugiat ut est nec auctor. Nulla vestibulum, ante sit amet rutrum ornare, turpis nunc laoreet felis, quis pellentesque

  - id: event-detail
    title: Event Details
    image: "content-image.jpg"
    description: Cras varius, nunc et maximus ullamcorper, tellus tellus posuere ipsum, ac tincidunt orci tortor id sapien. Vivamus ultrices purus id nisl volutpat, et placerat nisi ultricies. Integer at vehicula elit. Ut non velit non dui finibus finibus. Duis feugiat ut est nec auctor. Nulla vestibulum, ante sit amet rutrum ornare, turpis nunc laoreet felis, quis pellentesque

  - id: rsvp
    title: RSVP


